CC = g++
CFLAGS = -g -Wall -std=c++11
include filelist.mk
INCFLAGS =
LDFLAGS = -lcryptopp -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_program_options -lpthread
LIBS =

#check if AES-NI is supported by CPU
ifneq ($(shell grep -c aes /proc/cpuinfo),0)
	CPU_FLAGS = -maes -DAESNI
endif

