#!/bin/sh

# Copyright (c) 2013-2020, The PurpleI2P Project
#
# This file is part of Purple i2pd project and licensed under BSD3
#
# See full license text in LICENSE file at top of project tree
#
# That script written for use with Termux.

# https://stackoverflow.com/a/246128
SOURCE="${0}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

arch=$(uname -m)

screenfind=$(which screen)
if [ -z $screenfind ]; then
  echo "Can't find 'screen' installed. That script needs it!";
  exit 1;
fi

if [ -z i2pd-$arch ]; then
  echo "Can't find i2pd binary for your archtecture.";
  exit 1;
fi

screen -AmdS i2pd ./i2pd-$arch --datadir=$DIR
