#ifndef _VERSION_H_
#define _VERSION_H_

#define CODENAME "Opening"

#define STRINGIZE(x) #x
#define MAKE_VERSION(a,b,c) STRINGIZE(a) "." STRINGIZE(b) "." STRINGIZE(c)

#define DOTNET_VERSION_MAJOR 0
#define DOTNET_VERSION_MINOR 1
#define DOTNET_VERSION_MICRO 16
#define DOTNET_VERSION_PATCH 0
#define DOTNET_VERSION MAKE_VERSION(DOTNET_VERSION_MAJOR, DOTNET_VERSION_MINOR, DOTNET_VERSION_MICRO)
#define VERSION DOTNET_VERSION

#ifdef MESHNET
#define DOTNET_NET_ID 3
#else
#define DOTNET_NET_ID 2
#endif

#define DOTNET_VERSION_MAJOR 0
#define DOTNET_VERSION_MINOR 1
#define DOTNET_VERSION_MICRO 16
#define DOTNET_VERSION_PATCH 0
#define DOTNET_VERSION MAKE_VERSION(DOTNET_VERSION_MAJOR, DOTNET_VERSION_MINOR, DOTNET_VERSION_MICRO)

#endif
