name: Build Debian packages

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-deb.yml
    - contrib/**
    - daemon/**
    - debian/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Makefile
    - Makefile.linux
  pull_request:
    branches:
    - '*'
  workflow_call:

jobs:
  build:
    name: ${{ matrix.dist }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        dist: ['trixie']
        arch: ['amd64', 'arm64']
        include:
        - arch: amd64
          runner: ubuntu-latest
        - arch: arm64
          runner: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Commit Hash
      id: commit
      uses: prompt/actions-commit-hash@v3.0.0

    - name: Build package
      uses: jtdor/build-deb-action@v1
      with:
        docker-image: debian:${{ matrix.dist }}-slim
        buildpackage-opts: --build=binary --no-sign
        before-build-hook: debchange --controlmaint --local "${{ startsWith(github.ref, 'refs/tags/') && matrix.dist || format('+{0}~{1}', steps.commit.outputs.short, matrix.dist) }}" -b --distribution ${{ matrix.dist }} "CI build"
        extra-build-deps: devscripts git
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: i2pd_${{ matrix.dist }}_${{ matrix.arch }}
        path: debian/artifacts/i2pd_*.deb

    - name: Upload debugging symbols
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-dbgsym_${{ matrix.dist }}_${{ matrix.arch }}
        path: debian/artifacts/i2pd-dbgsym_*.deb
