name: Build on FreeBSD

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-freebsd.yml
    - build/CMakeLists.txt
    - build/cmake_modules/**
    - daemon/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Makefile
    - Makefile.bsd
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: FreeBSD ${{ matrix.release }} with UPnP

    strategy:
      fail-fast: false
      matrix:
        release: ['14.4', '15.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        release: ${{ matrix.release }}
        usesh: true
        mem: 2048
        sync: rsync
        copyback: true
        prepare: |
          sed -i '' 's|/quarterly"|/latest"|' /etc/pkg/FreeBSD.conf
          pkg update -f
          pkg install -y devel/cmake devel/gmake devel/boost-libs security/openssl35 net/miniupnpc
        run: |
          set -e
          cd build
          cmake -DWITH_UPNP=ON -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local .
          gmake -j2
          ./i2pd --version
          ./i2pd --version | grep -E '^OpenSSL (3\.([5-9]|[1-9][0-9])|[4-9])\.'
          ./i2pd --version | grep -E '^Boost version 1\.(8[1-9]|9[0-9])\.'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-freebsd-${{ matrix.release }}
        path: build/i2pd
