name: Build on FreeBSD

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-freebsd.yml
    - build/CMakeLists.txt
    - build/cmake_modules/**
    - daemon/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Makefile
    - Makefile.bsd
    - contrib/static/build-freebsd.sh
  pull_request:
    branches:
    - '*'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: FreeBSD ${{ matrix.release }} static

    strategy:
      fail-fast: false
      matrix:
        release: ['14.4', '15.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        release: ${{ matrix.release }}
        usesh: true
        mem: 4096
        sync: rsync
        copyback: true
        prepare: |
          sed -i '' 's|/quarterly"|/latest"|' /etc/pkg/FreeBSD.conf
          pkg update -f
          pkg install -y devel/cmake devel/gmake perl5 devel/boost-libs net/miniupnpc
        run: |
          set -e
          sh contrib/static/build-freebsd.sh
          file build/i2pd | grep 'statically linked'
          build/i2pd --version
          build/i2pd --version | grep -E '^OpenSSL (3\.([5-9]|[1-9][0-9])|[4-9])\.'
          build/i2pd --version | grep -E '^Boost version 1\.(8[1-9]|9[0-9])\.'
          mkdir /tmp/datadir
          build/i2pd --datadir=/tmp/datadir --log=file --logfile=/tmp/datadir/i2pd.log --loglevel=info &
          sleep 15
          kill -0 $!
          grep 'Daemon: Starting NetDB' /tmp/datadir/i2pd.log
          kill -9 $!

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-freebsd-${{ matrix.release }}
        path: build/i2pd
